SUDO: required
language: generic

services:
  - docker

before_install:
  - docker build -t madhu2264/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true madhu2264/docker-react npm run test
